// Getters
export const IS_REMAINING_TRACKS_TO_LOAD = 'IS_REMAINING_TRACKS_TO_LOAD';
export const NEXT_ALBUMS_INDEX_TO_LOAD = 'NEXT_ALBUMS_INDEX_TO_LOAD';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const GET_USER = 'GET_USER';
// Mutations
export const MUTATE_ARTIST_INFO = 'MUTATE_ARTIST_INFO';
export const MUTATE_ALBUMS = 'MUTATE_ALBUMS';
export const MUTATE_SELECTED_ALBUM = 'MUTATE_SELECTED_ALBUM';

export const MUTATE_SEARCH_LOADING_STATE = 'MUTATE_SEARCH_LOADING_STATE';
export const MUTATE_FOUND_TRACKS = 'MUTATE_FOUND_TRACKS';
export const MUTATE_ALBUMS_WITH_TRACKS = 'MUTATE_ALBUMS_WITH_TRACKS';
export const MUTATE_APPLICATION_BUSY_LOADING_TRACKS = 'MUTATE_APPLICATION_BUSY_LOADING_TRACKS';
export const MUTATE_CURRENTLY_PLAYING_TRACK = 'MUTATE_CURRENTLY_PLAYING_TRACK';

export const MUTATE_AUDIO_PLAYER_STATE = 'MUTATE_AUDIO_PLAYER_STATE';

export const MUTATE_USER_PLAYLISTS_LOADING_STATE = 'MUTATE_USER_PLAYLISTS_LOADING_STATE';
export const MUTATE_USER_PLAYLISTS = 'MUTATE_USER_PLAYLISTS';
export const MUTATE_CREATED_PLAYLIST = 'MUTATE_CREATED_PLAYLIST';
export const MUTATE_REMOVED_PLAYLIST = 'MUTATE_REMOVED_PLAYLIST';
export const MUTATE_NEW_PLAYLIST_NAME = 'MUTATE_NEW_PLAYLIST_NAME';
export const MUTATE_ADDED_TRACK_ON_PLAYLIST = 'MUTATE_ADDED_TRACK_ON_PLAYLIST';
export const MUTATE_DELETED_TRACK_ON_PLAYLIST = 'MUTATE_DELETED_TRACK_ON_PLAYLIST';

export const MUTATE_USER = 'MUTATE_USER';
export const MUTATE_AUTH_SUCCESS = 'MUTATE_AUTH_SUCCESS';
export const MUTATE_AUTH_ERROR = 'MUTATE_AUTH_ERROR';
export const MUTATE_LOGOUT = 'MUTATE_LOGOUT';
export const MUTATE_SEARCH_RESULT = 'MUTATE_SEARCH_RESULT';
export const MUTATE_SEARCH_TEXT_VALUE = 'MUTATE_SEARCH_TEXT_VALUE';
export const MUTATE_SEARCH_TYPE = 'MUTATE_SEARCH_TYPE';

export const MUTATE_SELECTED_USER = 'MUTATE_SELECTED_USER';
export const MUTATE_SELECTED_USER_LOADING_STATE = 'MUTATE_SELECTED_USER_LOADING_STATE';
export const MUTATE_IS_CURRENT_USER = 'MUTATE_IS_CURRENT_USER';
export const MUTATE_USER_IS_FOLLOWED = 'MUTATE_USER_IS_FOLLOWED';
export const MUTATE_FOLLOWED_USER = 'MUTATE_FOLLOWED_USER';
export const MUTATE_UNFOLLOWED_USER = 'MUTATE_UNFOLLOWED_USER';
export const MUTATE_SELECTED_USER_PLAYLIST = 'MUTATE_SELECTED_USER_PLAYLIST';
export const MUTATE_SELECTED_USER_PLAYLIST_LOADING_STATE = 'MUTATE_SELECTED_USER_PLAYLIST_LOADING_STATE';

// Actions
export const FETCH_ARTIST_INFO = 'FETCH_ARTIST_INFO';
export const FETCH_ARTIST_ALBUMS = 'FETCH_ARTIST_ALBUMS';
export const FETCH_SELECTED_ALBUM = 'FETCH_SELECTED_ALBUM';

export const GLOBAL_SEARCH = 'GLOBAL_SEARCH';
export const FETCH_ARTIST_ARTWORK = 'FETCH_ARTIST_ARTWORK';
export const SEARCH_USERS = 'SEARCH_USERS';

export const FIND_TRACKS = 'FIND_TRACKS';
export const FETCH_TRACKS_DYNAMICALLY = 'FETCH_TRACKS_DYNAMICALLY';
export const FETCH_SELECTED_ALBUM_TRACKS = 'FETCH_SELECTED_ALBUM_TRACKS';

export const SET_AUDIO_PLAYER_STATE = 'SET_AUDIO_PLAYER_STATE';
export const SET_CURRENTLY_PLAYING_TRACK = 'SET_CURRENTLY_PLAYING_TRACK';

export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
export const RENAME_PLAYLIST = 'RENAME_PLAYLIST';
export const ADD_TRACK_TO_PLAYLIST = 'ADD_TRACK_TO_PLAYLIST';
export const DELETE_TRACK_FROM_PLAYLIST = 'DELETE_TRACK_FROM_PLAYLIST';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';

export const UPDATE_USER = 'UPDATE_USER';
export const FETCH_SELECTED_USER = 'FETCH_SELECTED_USER';
export const LOOK_IF_USER_IS_CURRENT = 'LOOK_IF_USER_IS_CURRENT';
export const LOOK_IF_USER_IS_FOLLOWED = 'LOOK_IF_USER_IS_FOLLOWED';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const FETCH_SELECTED_USER_PLAYLIST = 'FETCH_SELECTED_USER_PLAYLIST';
